# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-07 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harryslist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Admin_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='harryslist.Admin'),
        ),
    ]
