# Generated by Django 2.0 on 2017-12-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harryslist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='Album_Name',
            field=models.CharField(max_length=32),
        ),
    ]
