# Generated by Django 2.0 on 2017-12-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harryslist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratealbums',
            name='Name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='ratealbums',
            name='Owner_User_ID',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='ratesongs',
            name='Rater_User_ID',
            field=models.CharField(max_length=32),
        ),
    ]
