# Generated by Django 2.0 on 2017-12-07 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harryslist', '0002_auto_20171207_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratealbums',
            name='Rater_User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='harryslist.Users'),
        ),
        migrations.AlterField(
            model_name='ratesongs',
            name='Rater_User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='harryslist.Users'),
        ),
    ]
