# Generated by Django 2.0 on 2017-12-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harryslist', '0003_auto_20171212_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratealbums',
            name='Rater_User_ID',
            field=models.CharField(max_length=32),
        ),
    ]
