# Generated by Django 2.0 on 2017-12-12 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harryslist', '0004_auto_20171212_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratealbums',
            name='Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='harryslist.Album'),
        ),
        migrations.AlterField(
            model_name='ratealbums',
            name='Owner_User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='harryslist.Artist'),
        ),
    ]
