# Generated by Django 2.0 on 2017-12-12 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harryslist', '0005_auto_20171212_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratealbums',
            name='Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harryslist.Album'),
        ),
        migrations.AlterField(
            model_name='ratealbums',
            name='Owner_User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harryslist.Artist'),
        ),
    ]
